# https://docs.github.com/en/actions/learn-github-actions/reusing-workflows

on:
  workflow_call:
    inputs:
      language:         # English, German, Spanish, etc.
        required: true
        type: string
      lang:   # en, de, es , etc.
        required: true
        type: string
      folder:
        required: true
        type: string
      pandocker-tag:
        required: false
        type: string
      pandocker-template:
        required: false
        type: string


jobs:
  doc-gen-reusable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Set VERSION to env 
      run: echo "VERSION=$(curl -s https://api.github.com/repos/OWASP/owasp-masvs/releases/latest | jq '.tag_name' | sed 's/\"//g')" >> $GITHUB_ENV


    - name: Set DEV VERSION if it's not a tag
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: echo "VERSION=${{env.VERSION}}-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Generate ${{ inputs.language }} PDF
      run: ${{ inputs.pandocker-tag }} ${{ inputs.pandocker-template }} ./tools/docker/pandoc_makedocs.sh ${{ inputs.folder }} ${{ env.VERSION }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-${{ env.VERSION }}-${{ inputs.lang }}
        path: OWASP_MASVS-${{ env.VERSION }}-${{ inputs.lang }}*
