name: Documents Build

on: [push, workflow_dispatch]

jobs:

##
## Use `pandocker-tag: TAG=latest-ubuntu-full` for langs that require the special fonts (Russian, Chinese, etc.)
##

  Generate-MASVS-Documents:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Set VERSION to env 
      run: echo "VERSION=$(curl -s https://api.github.com/repos/OWASP/owasp-masvs/tags | jq '.[0].name' | sed 's/\"//g')" >> $GITHUB_ENV

    - name: Set DEV VERSION if it's not a tag
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: echo "VERSION=${{env.VERSION}}-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Generate Markdown files from MASVS yaml
      run: python3 ./tools/generate_masvs_md.py

    - name: Generate PDF
      run: ./tools/docker/pandoc_makedocs.sh Document ${{ env.VERSION }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS
        path: OWASP_MASVS*

    - name: Upload YAML
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS.yaml
        path: masvs.yaml

  release:
    runs-on: ubuntu-latest
    needs: [Generate-MASVS-Documents]
    if: startsWith(github.ref, 'refs/tags/') && (github.actor == 'cpholguera' || github.actor == 'sushi2k')
    steps:
      - uses: actions/download-artifact@v2
      - name: List Downloaded document (sampling of download-artifact)
        run: ls -l OWASP_MASVS*

      - name: print working directory
        run: pwd 
      - name: Listing of root directory
        run: ls -l 

      - name: Move all translations (pdf, and epub) to root
        run: mv OWASP_MASVS*/* .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          draft: true
          generate_release_notes: true
          discussion_category_name: Announcements
          files: |
            OWASP_MASVS.pdf
            OWASP_MASVS.epub
            OWASP_MASVS.yaml/OWASP_MASVS.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
