name: Documents Build

on: [push, workflow_dispatch]

jobs:

##
## Use `pandocker-tag: TAG=stable-full` for langs that require the special fonts (Russian, Chinese, etc.)
##

  en:
    uses: OWASP/owasp-masvs/.github/workflows/doc-gen-reusable.yml
    with:
      folder: Document
      language: English
      lang: en

  de:
    uses: OWASP/owasp-masvs/.github/workflows/doc-gen-reusable.yml@master
    with:
      folder: Document-de
      language: German
      lang: de

  es:
    uses: OWASP/owasp-masvs/.github/workflows/doc-gen-reusable.yml@master
    with:
      folder: Document-es
      language: Spanish
      lang: es

  fr:
    uses: OWASP/owasp-masvs/.github/workflows/doc-gen-reusable.yml@master
    with:
      folder: Document-fr
      language: French
      lang: fr

  ptbr:
    uses: OWASP/owasp-masvs/.github/workflows/doc-gen-reusable.yml@master
    with:
      folder: Document-ptbr
      language: Brazilian Portuguese
      lang: ptbr

  ptpt:
    uses: OWASP/owasp-masvs/.github/workflows/doc-gen-reusable.yml@master
    with:
      folder: Document-ptpt
      language: Portugal Portuguese
      lang: ptpt

  hi:
    uses: OWASP/owasp-masvs/.github/workflows/doc-gen-reusable.yml@master
    with:
      folder: Document-hi
      language: Hindi
      lang: hi
      pandocker-tag: TAG=stable-full

  ja:
    uses: OWASP/owasp-masvs/.github/workflows/doc-gen-reusable.yml@master
    with:
      folder: Document-ja
      language: Japanese
      lang: ja
      pandocker-tag: TAG=stable-full

  ko:
    uses: OWASP/owasp-masvs/.github/workflows/doc-gen-reusable.yml@master
    with:
      folder: Document-ko
      language: Korean
      lang: ko
      pandocker-tag: TAG=stable-full

  ru:
    uses: OWASP/owasp-masvs/.github/workflows/doc-gen-reusable.yml@master
    with:
      folder: Document-ru
      language: Russian
      lang: ru
      pandocker-tag: TAG=stable-full

  fa:
    uses: OWASP/owasp-masvs/.github/workflows/doc-gen-reusable.yml@master
    with:
      folder: Document-fa
      language: Persian
      lang: fa
      pandocker-tag: TAG=stable-full
      pandocker-template: LATEX_TEMPLATE=default # there's a bug for fa in the eisvogel template, we have to use default

  zhcn:
    uses: OWASP/owasp-masvs/.github/workflows/doc-gen-reusable.yml@master
    with:
      folder: Document-zhcn
      language: Simplified Chinese
      lang: zhcn
      pandocker-tag: TAG=stable-full

  zhtw:
    uses: OWASP/owasp-masvs/.github/workflows/doc-gen-reusable.yml@master
    with:
      folder: Document-zhtw
      language: Traditional Chinese
      lang: zhtw
      pandocker-tag: TAG=stable-full

  export:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    # tag name with the number of additional commits on top of the tagged object 
    # and the abbreviated object name of the most recent commit
    - name: Set VERSION to env 
      run: echo "VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

    - name: Set DEV VERSION if it's not a tag
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: echo "VERSION=${{env.VERSION}}-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Install pyyaml
      run: pip3 install pyyaml

    - name: Generate CSV
      run: cd tools && python3 export.py --format csv --lang en > OWASP_MASVS-${{env.VERSION}}.csv
    - name: Generate JSON
      run: cd tools && python3 export.py --format json --lang en > OWASP_MASVS-${{env.VERSION}}.json
    - name: Generate XML
      run: cd tools && python3 export.py --format xml --lang en > OWASP_MASVS-${{env.VERSION}}.xml
    - name: Generate MASVS YAML
      run: cd tools && python3 export.py --format yaml --lang en > OWASP_MASVS-${{env.VERSION}}.yaml

    - name: Upload CSV
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-${{env.VERSION}}.csv
        path: tools/OWASP_MASVS-${{env.VERSION}}.csv
    - name: Upload JSON
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-${{env.VERSION}}.json
        path: tools/OWASP_MASVS-${{env.VERSION}}.json
    - name: Upload XML
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-${{env.VERSION}}.xml
        path: tools/OWASP_MASVS-${{env.VERSION}}.xml
    - name: Upload YAML
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-${{env.VERSION}}.yaml
        path: tools/OWASP_MASVS-${{env.VERSION}}.yaml

  release:
    runs-on: ubuntu-latest
    needs: [en, de, fa, es, fr, hi, ja, ko, ptbr, ptpt, ru, zhcn, zhtw, export]
    if: startsWith(github.ref, 'refs/tags/') && (github.actor == 'cpholguera' || github.actor == 'sushi2k')
    steps:
      - uses: actions/download-artifact@v2

      - name: Move all translations (pdf, epub and docx) to root
        run: mv OWASP_MASVS-*-*/* .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          draft: true
          generate_release_notes: true
          discussion_category_name: Announcements
          files: |
            OWASP_MASVS-*.pdf
            OWASP_MASVS-*.epub
            OWASP_MASVS-*.docx
            OWASP_MASVS-*.csv/OWASP_MASVS-*.csv
            OWASP_MASVS-*.json/OWASP_MASVS-*.json
            OWASP_MASVS-*.xml/OWASP_MASVS-*.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
