name: Documents Build

on: [push, workflow_dispatch]

env:
  VERSION: "1.3"

jobs:

##
## For langs that require the special fonts ( Russian, Chinese, etc.)
## The `stable-full` version of pandocker is required, you can activate
## it with the `TAG` environment variable, like this
##
## TAG=stable-full ./tools/docker/pandoc_makedocs.sh ....
##

  en:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate English PDF
      run: ./tools/docker/pandoc_makedocs.sh Document ${{env.VERSION}}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-${{env.VERSION}}-en
        path: OWASP_MASVS-${{env.VERSION}}-en*

  de:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate German PDF
      run: ./tools/docker/pandoc_makedocs.sh Document-de ${{env.VERSION}}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-${{env.VERSION}}-de
        path: OWASP_MASVS-${{env.VERSION}}-de*

  fa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate Persian PDF
      run: TAG=stable-full ./tools/docker/pandoc_makedocs.sh Document-fa ${{env.VERSION}}
      env:
        LATEX_TEMPLATE: default # there's a bug in the eisvogel template

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-${{env.VERSION}}-fa
        path: OWASP_MASVS-${{env.VERSION}}-fa*

  es:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate Spanish PDF
      run: ./tools/docker/pandoc_makedocs.sh Document-es ${{env.VERSION}}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-${{env.VERSION}}-es
        path: OWASP_MASVS-${{env.VERSION}}-es*

  fr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate French PDF
      run: ./tools/docker/pandoc_makedocs.sh Document-fr ${{env.VERSION}}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-${{env.VERSION}}-fr 
        path: OWASP_MASVS-${{env.VERSION}}-fr*

  hi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate Hindi PDF
      run: TAG=stable-full ./tools/docker/pandoc_makedocs.sh Document-hi ${{env.VERSION}}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-${{env.VERSION}}-hi
        path: OWASP_MASVS-${{env.VERSION}}-hi*

  ja:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate Japanese PDF
      run: TAG=stable-full ./tools/docker/pandoc_makedocs.sh Document-ja ${{env.VERSION}}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-${{env.VERSION}}-ja
        path: OWASP_MASVS-${{env.VERSION}}-ja*

  ko:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate Korean PDF
      run: TAG=stable-full ./tools/docker/pandoc_makedocs.sh Document-ko ${{env.VERSION}}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-${{env.VERSION}}-ko
        path: OWASP_MASVS-${{env.VERSION}}-ko*

  pt-br:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate Brazilian Portuguese PDF
      run: ./tools/docker/pandoc_makedocs.sh Document-ptbr ${{env.VERSION}}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-${{env.VERSION}}-ptbr
        path: OWASP_MASVS-${{env.VERSION}}-ptbr*


  pt-pt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate Portugal Portuguese PDF
      run: ./tools/docker/pandoc_makedocs.sh Document-ptpt ${{env.VERSION}}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-${{env.VERSION}}-ptpt
        path: OWASP_MASVS-${{env.VERSION}}-ptpt*


  ru:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate Russian PDF
      run: TAG=stable-full ./tools/docker/pandoc_makedocs.sh Document-ru ${{env.VERSION}}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-${{env.VERSION}}-ru
        path: OWASP_MASVS-${{env.VERSION}}-ru*

  zhcn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate Simplified Chinese PDF
      run: TAG=stable-full ./tools/docker/pandoc_makedocs.sh Document-zhcn ${{env.VERSION}}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-${{env.VERSION}}-zhcn
        path: OWASP_MASVS-${{env.VERSION}}-zhcn*

  zhtw:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate Traditional Chinese PDF
      run: TAG=stable-full ./tools/docker/pandoc_makedocs.sh Document-zhtw ${{env.VERSION}}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-${{env.VERSION}}-zhtw
        path: OWASP_MASVS-${{env.VERSION}}-zhtw*


  export:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Pull the Docker image
      run: docker pull owasp/masvs-docgenerator:0.2
    # only use below when testing new container builds
    # - name: Build the Docker image
    #   run: docker build ./tools/docker --tag masvs-generator:latest

    - name: Generate python scripts (csv)
      run: docker run -v ${PWD}:/documents owasp/masvs-docgenerator:0.2 'cd /documents/tools && python3 export.py --format csv --lang en > OWASP_MASVS-${{env.VERSION}}.csv'
    - name: Generate python scripts (json)
      run: docker run -v ${PWD}:/documents owasp/masvs-docgenerator:0.2 'cd /documents/tools && python3 export.py --format json --lang en > OWASP_MASVS-${{env.VERSION}}.json'
    - name: Generate python scripts (xml)
      run: docker run -v ${PWD}:/documents owasp/masvs-docgenerator:0.2 'cd /documents/tools && python3 export.py --format xml --lang en > OWASP_MASVS-${{env.VERSION}}.xml'
    - name: Upload CSV export
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-${{env.VERSION}}.csv
        path: tools/OWASP_MASVS-${{env.VERSION}}.csv
    - name: Upload JSON export
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-${{env.VERSION}}.json
        path: tools/OWASP_MASVS-${{env.VERSION}}.json
    - name: Upload XML export
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-${{env.VERSION}}.xml
        path: tools/OWASP_MASVS-${{env.VERSION}}.xml

    - name: Upload RECENT Changes
      uses: actions/upload-artifact@v2
      if: startsWith(github.ref, 'refs/tags/') && (github.actor == 'cpholguera' || github.actor == 'sushi2k')
      with:
        name: RECENT_CHANGES.md
        path: tools/RECENT_CHANGES.md

  release:
    runs-on: ubuntu-latest
    needs: [en, de, fa, es, fr, hi, ja, ko, pt-br, pt-pt, ru, zhcn, zhtw, export]
    if: startsWith(github.ref, 'refs/tags/') && (github.actor == 'cpholguera' || github.actor == 'sushi2k')
    steps:
      - uses: actions/download-artifact@v2
      - name: List ES
        run: ls -l OWASP_MASVS-*-es
      - name: Unpack
        run: mv OWASP_MASVS-*-*/* .
      - name: List
        run: ls -l
      - name: Cleanup 
        run: rm -rf OWASP_MASVS-*/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: RECENT_CHANGES.md
          files: |
            OWASP_MASVS-*.pdf
            OWASP_MASVS-*.epub
            OWASP_MASVS-*.docx
            OWASP_MASVS-*.csv
            OWASP_MASVS-*.json
            OWASP_MASVS-*.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

